<a href="https://colab.research.google.com/github/shaikharaina/Storm-/blob/main/Rahat_NOAA_Storm_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Load the CSV files

In [2]:
# define the paths
TRAIN_CSV = "/content/drive/MyDrive/RP_Training_Tabular/Artifacts/train.csv"

In [3]:
import pandas as pd

# load the train csv
data_train = pd.read_csv(TRAIN_CSV)
data_train.head()

,MAGNITUDE,TOR_F_SCALE_NUM,TOR_LENGTH,TOR_WIDTH,BEGIN_LAT,BEGIN_LON,DURATION_SECONDS,IS_NIGHT,EVENT_GROUP_Convective_Severe,EVENT_GROUP_Heat_Drought,EVENT_GROUP_Hydrological,EVENT_GROUP_Marine,EVENT_GROUP_Other,EVENT_GROUP_Winter,HAS_DAMAGE
0,0.0,-1.0,0.0,0.0,39.38,-85.83,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0,0
1,1.5,-1.0,0.0,0.0,41.10,-98.22,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
2,55.0,-1.0,0.0,0.0,43.90,-75.93,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
3,63.0,-1.0,0.0,0.0,41.12,-95.90,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0
4,0.0,-1.0,0.0,0.0,39.82,-75.62,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0,0

Encoding Labels

In [4]:
LABEL_COLUMN = "HAS_DAMAGE"

In [5]:
# labels are there as string otherwise words
# need to convert the labels into numbers
print(data_train[LABEL_COLUMN].value_counts())
LABELS = list(data_train[LABEL_COLUMN].unique())
# sort the labels
LABELS.sort()
print(LABELS)

HAS_DAMAGE
0    129972
1     21318
Name: count, dtype: int64
[np.int64(0), np.int64(1)]

In [6]:
# convert into numbers
data_train[LABEL_COLUMN] = pd.factorize(data_train[LABEL_COLUMN], sort = True)[0]
data_train[LABEL_COLUMN].value_counts()

HAS_DAMAGE
0    129972
1     21318
Name: count, dtype: int64

Seperate features and labels

In [7]:
# get all features without the labels
# all the rows
# all the columns without the last column
X = data_train.drop(LABEL_COLUMN, axis = 1).values
# all rows
# only the lastb column, which is the label
Y = data_train[LABEL_COLUMN].values

Train the Model using Cross Validation

In [8]:

from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, precision_score, recall_score
import numpy as np

def cross_validation(model, data = (X, Y), splits = 5):
    kf = KFold(n_splits=splits, shuffle=True, random_state=42)

    # Perform k-fold cross-validation
    accuracy = []
    precision = []
    recall = []

    for train_index, valid_index in kf.split(data[0]):
        X_train, X_valid = data[0][train_index], data[0][valid_index]
        y_train, y_valid = data[1][train_index], data[1][valid_index]

        # Fit the defined model
        model.fit(X_train, y_train)

        # Make predictions on the test data
        y_pred = model.predict(X_valid)

        # Calculate accuracy, precision and recall
        accuracy.append(accuracy_score(y_pred, y_valid))
        precision.append(precision_score(y_pred, y_valid, average = 'macro'))
        recall.append(recall_score(y_pred, y_valid, average = 'macro'))


    # get arrays
    accuracy_set = np.array(accuracy)
    precision_set = np.array(precision)
    recall_set = np.array(recall)

    print("Mean Accuracy: {}".format(accuracy_set.mean()))
    print("Mean Precision: {}".format(precision_set.mean()))
    print("Mean Recall: {}".format(recall_set.mean()))

Logistic Regression

In [ ]:
# from sklearn.linear_model import LogisticRegression

# # fit the logistic regression
# lr = LogisticRegression()

# cross_validation(lr)

In [9]:
from sklearn.linear_model import LogisticRegression

c_list = [0.01, 0.1, 1, 10, 100]
max_iter_list = [100, 200, 300, 400, 500]

for c in range (0,5):
  for max_iter in range(0,5):
    print("C: " + str(c_list[c]))
    print("Max_iter: " + str(max_iter_list[max_iter]))
    lr = LogisticRegression(max_iter = max_iter_list[max_iter], C = c_list[c])

C: 0.01
Max_iter: 100
C: 0.01
Max_iter: 200
C: 0.01
Max_iter: 300
C: 0.01
Max_iter: 400
C: 0.01
Max_iter: 500
C: 0.1
Max_iter: 100
C: 0.1
Max_iter: 200
C: 0.1
Max_iter: 300
C: 0.1
Max_iter: 400
C: 0.1
Max_iter: 500
C: 1
Max_iter: 100
C: 1
Max_iter: 200
C: 1
Max_iter: 300
C: 1
Max_iter: 400
C: 1
Max_iter: 500
C: 10
Max_iter: 100
C: 10
Max_iter: 200
C: 10
Max_iter: 300
C: 10
Max_iter: 400
C: 10
Max_iter: 500
C: 100
Max_iter: 100
C: 100
Max_iter: 200
C: 100
Max_iter: 300
C: 100
Max_iter: 400
C: 100
Max_iter: 500

KNN

In [10]:
# from sklearn.neighbors import KNeighborsClassifier

# # Use 5-fold cross validation for hyper-parameter tuning
# # Try out different values and choose the best hyper-parameters
# knn = KNeighborsClassifier(n_neighbors=10)

# cross_validation(knn)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

for i in range(1,21):
  print("Iteration " + str(i))
  knn = KNeighborsClassifier(n_neighbors=i)
  cross_validation(knn)

Iteration 1
Mean Accuracy: 0.9544451054266639
Mean Precision: 0.9037976429156604
Mean Recall: 0.9072635973708965
Iteration 2
Mean Accuracy: 0.9461365589265649
Mean Precision: 0.8503194408266157
Mean Recall: 0.9167039566458378
Iteration 3
Mean Accuracy: 0.958404388921938
Mean Precision: 0.9210354951058601
Mean Recall: 0.9097171354386934
Iteration 4
Mean Accuracy: 0.9559918038204772
Mean Precision: 0.8960947493941678
Mean Recall: 0.9181414929840269
Iteration 5
Mean Accuracy: 0.9592834952739772
Mean Precision: 0.9248623254820443
Mean Recall: 0.9102785296685875
Iteration 6
Mean Accuracy: 0.9577632361689471
Mean Precision: 0.9073590198572388
Mean Recall: 0.916414279176967
Iteration 7
Mean Accuracy: 0.9598122810496397
Mean Precision: 0.9273533117713111
Mean Recall: 0.9105188428972874
Iteration 8
Mean Accuracy: 0.9586357326987903
Mean Precision: 0.9137260556692919
Mean Recall: 0.9151286754782875
Iteration 9
Mean Accuracy: 0.9600568444708838
Mean Precision: 0.9288893166578438
Mean Recall: 0.9103984128330511
Iteration 10
Mean Accuracy: 0.9594355211844802
Mean Precision: 0.9182466179791449
Mean Recall: 0.9148795174762666
Iteration 11
Mean Accuracy: 0.9603080177143235
Mean Precision: 0.9300269793254762
Mean Recall: 0.9105265881834596
Iteration 12
Mean Accuracy: 0.9595941569171789
Mean Precision: 0.9205093679771803
Mean Recall: 0.9139622790960109
Iteration 13
Mean Accuracy: 0.9601692114482121
Mean Precision: 0.9303555324457587
Mean Recall: 0.9098958915395468
Iteration 14
Mean Accuracy: 0.9593958622513054
Mean Precision: 0.9215240427522113
Mean Recall: 0.9126607146405797
Iteration 15
Mean Accuracy: 0.9600502346486879
Mean Precision: 0.9303327816851649
Mean Recall: 0.9095218041503838
Iteration 16
Mean Accuracy: 0.9597527926498778
Mean Precision: 0.9233650516877873
Mean Recall: 0.912701765365709
Iteration 17
Mean Accuracy: 0.9599643069601427
Mean Precision: 0.9305005194181515
Mean Recall: 0.9091621519845043
Iteration 18
Mean Accuracy: 0.9597329631832903
Mean Precision: 0.9244035606134412
Mean Recall: 0.9119964545287742
Iteration 19
Mean Accuracy: 0.9598585498050103
Mean Precision: 0.9304009872554355
Mean Recall: 0.9088897885526916
Iteration 20
Mean Accuracy: 0.9594619604732634
Mean Precision: 0.9245412724160426
Mean Recall: 0.9110376249644636

Random Forest

In [12]:
#from sklearn.ensemble import RandomForestClassifier

## Use 5-fold cross validation for hyper-parameter tuning
## Try out different values and choose the best hyper-parameters
#rf = RandomForestClassifier()

#cross_validation(rf)

In [13]:
from sklearn.ensemble import RandomForestClassifier

n_list = [10,20,30,40,50,60,70,80,90,100]
depth_list = [1,2,3,4,5,6,7]

for n in range(0,10):
  for depth in range(0,7):
    print("N_estimators: " + str(n_list[n]))
    print("Max_depth: " + str(depth_list[depth]))
    rf = RandomForestClassifier(n_estimators = n_list[n], max_depth = depth_list[depth])
    cross_validation(rf)

N_estimators: 10
Max_depth: 1

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Mean Accuracy: 0.9264525084275232
Mean Precision: 0.8232915273784815
Mean Recall: 0.7841685863893245
N_estimators: 10
Max_depth: 2
Mean Accuracy: 0.9498578888227908
Mean Precision: 0.944143977385426
Mean Recall: 0.8760105747093938
N_estimators: 10
Max_depth: 3
Mean Accuracy: 0.9506775067750677
Mean Precision: 0.9551166051206567
Mean Recall: 0.8749925966481763
N_estimators: 10
Max_depth: 4
Mean Accuracy: 0.9563685636856369
Mean Precision: 0.9552032676992482
Mean Recall: 0.8885306634410188
N_estimators: 10
Max_depth: 5
Mean Accuracy: 0.959495009584242
Mean Precision: 0.9462460942873108
Mean Recall: 0.899885431256004
N_estimators: 10
Max_depth: 6
Mean Accuracy: 0.960261748958953
Mean Precision: 0.9455302012547355
Mean Recall: 0.9023959995026548
N_estimators: 10
Max_depth: 7
Mean Accuracy: 0.9613589794434529
Mean Precision: 0.945547379107472
Mean Recall: 0.9054121217954526
N_estimators: 20
Max_depth: 1
Mean Accuracy: 0.9277414237557011
Mean Precision: 0.8450861432408174
Mean Recall: 0.8416906236972693
N_estimators: 20
Max_depth: 2
Mean Accuracy: 0.9492563950029744
Mean Precision: 0.9613295679039687
Mean Recall: 0.8696278352103199
N_estimators: 20
Max_depth: 3
Mean Accuracy: 0.9544715447154472
Mean Precision: 0.9576443639026866
Mean Recall: 0.8826276681552778
N_estimators: 20
Max_depth: 4
Mean Accuracy: 0.9571551325269348
Mean Precision: 0.9515540647051747
Mean Recall: 0.8916203289008152
N_estimators: 20
Max_depth: 5
Mean Accuracy: 0.959495009584242
Mean Precision: 0.9489339272564244
Mean Recall: 0.8987606052165182
N_estimators: 20
Max_depth: 6
Mean Accuracy: 0.9608566329565734
Mean Precision: 0.947535608267209
Mean Recall: 0.9030284343009125
N_estimators: 20
Max_depth: 7
Mean Accuracy: 0.9613127106880824
Mean Precision: 0.9440701412469006
Mean Recall: 0.9060102378803784
N_estimators: 30
Max_depth: 1
Mean Accuracy: 0.9435917773811886
Mean Precision: 0.9123787418992538
Mean Recall: 0.8710798662178373
N_estimators: 30
Max_depth: 2
Mean Accuracy: 0.9499239870447486
Mean Precision: 0.9628719325396068
Mean Recall: 0.8707911804460325
N_estimators: 30
Max_depth: 3
Mean Accuracy: 0.9524423293013417
Mean Precision: 0.958209648807793
Mean Recall: 0.8775232058131707
N_estimators: 30
Max_depth: 4
Mean Accuracy: 0.9574525745257452
Mean Precision: 0.9544513050724571
Mean Recall: 0.890911375809293
N_estimators: 30
Max_depth: 5
Mean Accuracy: 0.959164518474453
Mean Precision: 0.9502192573547539
Mean Recall: 0.8971916306977287
N_estimators: 30
Max_depth: 6
Mean Accuracy: 0.9606054597131337
Mean Precision: 0.9471545271575152
Mean Recall: 0.9024710327838458
N_estimators: 30
Max_depth: 7
Mean Accuracy: 0.9615969330425012
Mean Precision: 0.9438945564886524
Mean Recall: 0.906967911583072
N_estimators: 40
Max_depth: 1
Mean Accuracy: 0.9439090488465862
Mean Precision: 0.9136246347251549
Mean Recall: 0.8714319757518096
N_estimators: 40
Max_depth: 2
Mean Accuracy: 0.950882411263137
Mean Precision: 0.9593674967041445
Mean Recall: 0.8740530005071292
N_estimators: 40
Max_depth: 3
Mean Accuracy: 0.9520787890805738
Mean Precision: 0.9597046829649181
Mean Recall: 0.8763459122378988
N_estimators: 40
Max_depth: 4
Mean Accuracy: 0.9577367968801639
Mean Precision: 0.9536001806225585
Mean Recall: 0.8920096122548564
N_estimators: 40
Max_depth: 5
Mean Accuracy: 0.9597329631832905
Mean Precision: 0.9502856592527898
Mean Recall: 0.8987182145584793
N_estimators: 40
Max_depth: 6
Mean Accuracy: 0.9612201731773415
Mean Precision: 0.9479295536609925
Mean Recall: 0.9038749891917297
N_estimators: 40
Max_depth: 7
Mean Accuracy: 0.9615771035759139
Mean Precision: 0.9448779045093175
Mean Recall: 0.906391025058355
N_estimators: 50
Max_depth: 1
Mean Accuracy: 0.9425474254742549
Mean Precision: 0.9017044494812023
Mean Recall: 0.8719562373977159
N_estimators: 50
Max_depth: 2
Mean Accuracy: 0.9512393416617092
Mean Precision: 0.9582591356259427
Mean Recall: 0.8748471609482396
N_estimators: 50
Max_depth: 3
Mean Accuracy: 0.9526935025447816
Mean Precision: 0.9590112843986539
Mean Recall: 0.8780055770724069
N_estimators: 50
Max_depth: 4
Mean Accuracy: 0.9571815718157183
Mean Precision: 0.9544579304262101
Mean Recall: 0.8902617477985864
N_estimators: 50
Max_depth: 5
Mean Accuracy: 0.9593892524291097
Mean Precision: 0.9507877893731937
Mean Recall: 0.8975405549883224
N_estimators: 50
Max_depth: 6
Mean Accuracy: 0.9612928812214951
Mean Precision: 0.945920982513357
Mean Recall: 0.9050745316965063
N_estimators: 50
Max_depth: 7
Mean Accuracy: 0.9615308348205434
Mean Precision: 0.9445849955117473
Mean Recall: 0.906389017732893
N_estimators: 60
Max_depth: 1
Mean Accuracy: 0.9251503734549541
Mean Precision: 0.8198467496868499
Mean Recall: 0.8426099711420074
N_estimators: 60
Max_depth: 2
Mean Accuracy: 0.9508427523299623
Mean Precision: 0.9591119063203097
Mean Recall: 0.8737207212762437
N_estimators: 60
Max_depth: 3
Mean Accuracy: 0.9516623702822395
Mean Precision: 0.9616893761397126
Mean Recall: 0.8749615164113956
N_estimators: 60
Max_depth: 4
Mean Accuracy: 0.9570890343049772
Mean Precision: 0.9548530319264049
Mean Recall: 0.8898661922118976
N_estimators: 60
Max_depth: 5
Mean Accuracy: 0.9601295525150373
Mean Precision: 0.9500849587249286
Mean Recall: 0.8997923430731353
N_estimators: 60
Max_depth: 6
Mean Accuracy: 0.9611937338885583
Mean Precision: 0.9454580579888454
Mean Recall: 0.9049759797775667
N_estimators: 60
Max_depth: 7
Mean Accuracy: 0.9614316874876065
Mean Precision: 0.9448821449450382
Mean Recall: 0.9059652107546551
N_estimators: 70
Max_depth: 1
Mean Accuracy: 0.9420979575649415
Mean Precision: 0.8991166392762648
Mean Recall: 0.8717793826165245
N_estimators: 70
Max_depth: 2
Mean Accuracy: 0.9498909379337694
Mean Precision: 0.9607721091262398
Mean Recall: 0.8711912616016239
N_estimators: 70
Max_depth: 3
Mean Accuracy: 0.9521713265913148
Mean Precision: 0.9599462510093005
Mean Recall: 0.8765315158297445
N_estimators: 70
Max_depth: 4
Mean Accuracy: 0.9578425540352965
Mean Precision: 0.9529450452850291
Mean Recall: 0.8926282482020967
N_estimators: 70
Max_depth: 5
Mean Accuracy: 0.9590521514971246
Mean Precision: 0.9514106652852206
Mean Recall: 0.8963052956216014
N_estimators: 70
Max_depth: 6
Mean Accuracy: 0.9612069535329499
Mean Precision: 0.9461212759925692
Mean Recall: 0.9046873287754037
N_estimators: 70
Max_depth: 7
Mean Accuracy: 0.9615969330425009
Mean Precision: 0.9448600869735093
Mean Recall: 0.9064556621395333
N_estimators: 80
Max_depth: 1
Mean Accuracy: 0.9432348469826162
Mean Precision: 0.9054385029218736
Mean Recall: 0.872324853359215
N_estimators: 80
Max_depth: 2
Mean Accuracy: 0.949144028025646
Mean Precision: 0.9619505610532053
Mean Recall: 0.8692415640159743
N_estimators: 80
Max_depth: 3
Mean Accuracy: 0.9533875338753388
Mean Precision: 0.9577866415821127
Mean Recall: 0.8799094869951072
N_estimators: 80
Max_depth: 4
Mean Accuracy: 0.9579483111904288
Mean Precision: 0.9544984926837895
Mean Recall: 0.8922293028775907
N_estimators: 80
Max_depth: 5
Mean Accuracy: 0.9600436248264922
Mean Precision: 0.9496890214705637
Mean Recall: 0.8998017793861918
N_estimators: 80
Max_depth: 6
Mean Accuracy: 0.9611408553109921
Mean Precision: 0.946831439315963
Mean Recall: 0.9041742245045414
N_estimators: 80
Max_depth: 7
Mean Accuracy: 0.9614515169541938
Mean Precision: 0.9447856675829156
Mean Recall: 0.9060755568275516
N_estimators: 90
Max_depth: 1
Mean Accuracy: 0.9434595809372727
Mean Precision: 0.9116197019555807
Mean Recall: 0.8714037089773216
N_estimators: 90
Max_depth: 2
Mean Accuracy: 0.950882411263137
Mean Precision: 0.958524062334018
Mean Recall: 0.8739894090837108
N_estimators: 90
Max_depth: 3
Mean Accuracy: 0.9516888095710225
Mean Precision: 0.9616210848518982
Mean Recall: 0.8748634800515139
N_estimators: 90
Max_depth: 4
Mean Accuracy: 0.957062595016194
Mean Precision: 0.9544690450722328
Mean Recall: 0.8899153040233297
N_estimators: 90
Max_depth: 5
Mean Accuracy: 0.9601229426928416
Mean Precision: 0.9502158884832113
Mean Recall: 0.899752753773428
N_estimators: 90
Max_depth: 6
Mean Accuracy: 0.9608301936677904
Mean Precision: 0.9478404365590146
Mean Recall: 0.9028107442959394
N_estimators: 90
Max_depth: 7
Mean Accuracy: 0.9616167625090885
Mean Precision: 0.944836095002682
Mean Recall: 0.9065123031429982
N_estimators: 100
Max_depth: 1
Mean Accuracy: 0.9420649084539626
Mean Precision: 0.8989978866378273
Mean Recall: 0.8717349296940344
N_estimators: 100
Max_depth: 2
Mean Accuracy: 0.9509947782404653
Mean Precision: 0.9593737036511654
Mean Recall: 0.8739938657519237
N_estimators: 100
Max_depth: 3
Mean Accuracy: 0.952098618547161
Mean Precision: 0.9603375269526178
Mean Recall: 0.8762665192488109
N_estimators: 100
Max_depth: 4
Mean Accuracy: 0.9572410602154802
Mean Precision: 0.9546031435057147
Mean Recall: 0.8903316711003854
N_estimators: 100
Max_depth: 5
Mean Accuracy: 0.9600436248264922
Mean Precision: 0.9507732087348085
Mean Recall: 0.8992878249621402
N_estimators: 100
Max_depth: 6
Mean Accuracy: 0.961325930332474
Mean Precision: 0.9474895258824558
Mean Recall: 0.9043700543798815
N_estimators: 100
Max_depth: 7
Mean Accuracy: 0.9616167625090885
Mean Precision: 0.9443061634300637
Mean Recall: 0.9067948227526064

Fit the best model


*   Select the best model having the highest cross validation accuracy

In [14]:
# Model with the lowest RMSE or highest r2
best_model = RandomForestClassifier()

# Fit the model on the full training dataset
best_model.fit(X, Y)

RandomForestClassifier()

Save the best model


*   Make sure to donwload the model when you are planning to use the model later.

In [16]:
import os

ARTIFACTS_PATH = '/content/drive/MyDrive/RP_Training_Tabular/Artifacts'

os.makedirs(ARTIFACTS_PATH, exist_ok=True)

BEST_MODEL_PATH = os.path.join(
    ARTIFACTS_PATH,
    'best_model.pkl'
)

print(BEST_MODEL_PATH)

/content/drive/MyDrive/RP_Training_Tabular/Artifacts/best_model.pkl

In [17]:
import pickle

BEST_MODEL_PATH = '/content/drive/MyDrive/RP_Training_Tabular/Artifacts/best_model.pkl'

with open(BEST_MODEL_PATH, 'wb') as fh:
    pickle.dump(best_model, fh)

print("Best model saved successfully!")
print(BEST_MODEL_PATH)

Best model saved successfully!
/content/drive/MyDrive/RP_Training_Tabular/Artifacts/best_model.pkl